### ISSUE TITLE
Add Poetry pre-commit hooks

### ISSUE THREAD

**Issue by alejandroarmas** [alejandroarmas/some-dl-models#19]
[Source](https://python-poetry.org/docs/pre-commit-hooks/)

Hope this is a good forcing function to familiarize yourself with a pre-commit hook. Add this to the `.pre-commit-config.yaml` and demonstrate that it generates a requirements file.  

```
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: ''  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

```
